services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
      - rabbitmq

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - api
    env_file:
      - .env

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    ports:
      - "${AI_PORT}:${AI_PORT}"
    depends_on:
      - rabbitmq
    env_file:
      - .env

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
