services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:${RABBITMQ_MANAGEMENT_PORT:-15672}"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - elasticsearch

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    ports:
      - "${CLIENT_PORT:-4000}:80"
    depends_on:
      - api
    env_file:
      - .env

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    ports:
      - "${AI_PORT:-3030}:${AI_PORT:-3030}"
    depends_on:
      - rabbitmq
      - ollama
    env_file:
      - .env

  ollama:
    image: ollama/ollama
    container_name: ollama
    env_file:
      - .env
    ports:
      - "${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  translator:
    build:
      context: ./translator
      dockerfile: Dockerfile
    container_name: translator
    env_file:
      - .env
    ports:
      - "${GO_SERVICE_PORT:-8000}:8000"
    depends_on:
      - rabbitmq
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:${ELASTICSEARCH_PORT:-9200}"
      - "${ELASTICSEARCH_TRANSPORT_PORT:-9300}:${ELASTICSEARCH_TRANSPORT_PORT:-9300}"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  postgres_slave:
    build:
      context: ./postgres-slave
    container_name: postgres_slave
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_slave_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
  ollama_data:
  redis_data:
  esdata:
  postgres_slave_data:

networks:
  default:
    driver: bridge
